project:
  type: website
  output-dir: docs

website:
  title: "Brightsparx"
  favicon: Images/favicon.jpeg
  navbar:
    logo: Images/favicon.jpeg
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: services.qmd
        text: Services
      - href: industries.qmd
        text: Industries
      - href: contact.qmd
        text: Contact
  page-footer:
    right: © 2024 Brightsparx. All rights reserved.
    background: light


format:
  html:
    theme:
      - cerulean
      - brand
    css: styles.css
    toc: true
    page-layout: full
  


