project:
  type: website
  output-dir: docs

website:
  title: Brightsparx Group
  favicon: Images/favicon.jpeg
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: services.qmd
        text: Services
      - href: industries.qmd
        text: Industries
      - href: contact.qmd
        text: Contact
  page-footer:
    right: © 2024 Brightsparx. All rights reserved.
    background: light


format:
  html:
    theme:
      light: styles.scss
    fontsize: 3.5em
    toc: false
    page-layout: full
  
  # To have the styles consistent across all pages, just have everything refer to the SCSS file? Use this 
  # as the SoT for all formats.
  # Then in the above section of all pages have css as Styles.css.


