project:
  type: website
  output-dir: docs

website:
  title: "Brightsparx Group"
  favicon: Images/favicon.jpeg
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: services.qmd
        text: Services
      - href: industries.qmd
        text: Industries
      - href: contact.qmd
        text: Contact
  page-footer:
    right: © 2024 Brightsparx. All rights reserved.
    background: light


format:
  html:
    theme:
      light: cerulean
      dark: superhero
    fontsize: 3.5em
    css: styles.css
    toc: true
    page-layout: full
  


